### PR TITLE
updated to 2019.1.0.post0

### PR DESCRIPTION
**Pull request by g-voelker**
moved hypre, parmetis and scotch to AUR submodules; moved sympy to community

### CODE REVIEW

**Comment by sigvaldm** [comment]
The custom `-sm` packages are there to fix issues with the packages in AUR (as well as solving dependency issues). So I had a brief look in the AUR comments sections of the packages to see why I made the `-sm` packages in the first place. Let me address them separately.

`python-sympy-sm`: This one we've established can be removed in favor of the one in community.

`hypre-sm`: The version on AUR at the time was not new enough for FEniCS, so I made an updated one. This appears not to be an issue anymore so `hypre-sm` should be replaced by AUR `hypre` as you suggest.

`scotch-sm`: Since the one on AUR worked for you I take it that you're on a quad-core computer. However, if you read the comments on AUR it does not work on dual-core computers because OpenMPI gives an error if you try to use more processes than you have cores (older versions of OpenMPI didn't do this). `scotch-sm` is the exact same package as the one on AUR except that it uses `sed` to add the flag `--oversubscribe` to `mpirun` in one of Scotch's makefiles when running tests. There has been new versions of Scotch since, but this bug appears not to be fixed. I suggest keeping `scotch-sm`, but updating it to the same version as the one you used from AUR. A diff between the two would reveal which things ought to be updated in `scotch-sm`, I think.

`hypre-sm`: I had some conflicts between `hypre` and `mumps-par` and managed to fix it by changing this package. In hindsight, I probably did some unfortunate changes to this package although I've never had problems with it myself. It is probably `mumps-par` that should've been changed, which is even more out-of-date now then it was back then. Do you use `mumps-par`, by the way? If you do then I suppose the error no longer persists and we can safely remove `hypre-sm` and switch to `hypre` on AUR. If not we should still move to `hypre` on AUR since `hypre-sm` is bad. But then someone would have to check if `mumps-par` works with FEniCS, and if not make an `mumps-par-sm` package. I won't request that as part of this PR.

**Comment by sigvaldm** [comment]
One more thing: I noticed that the submodules for FEniCS are still pointing to the same commit before and after this PR, i.e., the 2018.1.0 version. You probably wanted them (and maybe other submodules as well) to point to the most recent version in AUR. Once you've checked out the correct version of the submodules you need to add and commit them to this repo. Their contents will not be added, only the commit hash they point to.

Thanks for your efforts, by the way.

**Comment by sigvaldm** [comment]
@g-voelker: Are you still active on this?

**Comment by g-voelker** [comment]
Yeah - still on it, just had a lot of things up my plate lately. I am trying to get to it in the next couple of days, latest in two weeks.

**Comment by g-voelker** [comment]
I sadly never finished on this, thus closing the pull request.

**Pull request closed without merging**
